version: '3.8'
services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NAME=example
    depends_on:
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.9.0
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
    command: ["-config.file=/etc/promtail/config.yml"]
    depends_on:
      - loki

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
